### ISSUE TITLE
Farben für den Consent Manager im Backend einstellen?

### ISSUE THREAD

**Issue by eaCe** [alexplusde/wenns_sein_muss#37]
Man könnte diese im Optik-Tab einstellen und in der bereits vorhandenen wsm.css.php ausgeben.

**Comment by alxndr-w** [comment]
Solange das nicht ausartet wie beim consent manager mit — imho furchtbaren Design- und UX-Verfehlungen — bin ich da offen.

**Comment by alxndr-w** [comment]
Ausgabe für CSS und JS müssten auch um nonce ergänzt werden...

**Comment by alxndr-w** [comment]
Einen PR dazu nehme ich gerne an, aber das Issue wird aus Übersichtsgründen geschlossen

**Comment by eaCe** [comment]
Ja, ist auch ein wenig Aufwand für etwas das man auch einfach via css lösen kann. Da ich keine Seite mit Consent habe, muss ich schauen ob ich das irgendwann mal so bastel
