### ISSUE TITLE
Installationsabbruch

### ISSUE THREAD

**Issue by christophboecker** [alexplusde/wenns_sein_muss#57]
ich laufe beim Installieren auf diesen Fehler:

AddOn wenns_sein_muss konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "CREATE TABLE `rex_wenns_sein_muss_iframe` ( `id` int(10) unsigned NOT NULL auto_increment , `embedUrl` text DEFAULT '\'\'' NOT NULL , `key` varchar(191) DEFAULT '' NOT NULL , PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;" using params []! SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'embedUrl' can't have a default value

https://github.com/alexplusde/wenns_sein_muss/blob/2953aa60f994ab719a6bf47cfba5f2f0e8eaf6d2/install.php#L33

Redaxo 5.17.1
PHP 8.2.16
MySQL 8.0.28

Geändert in 
```php
->ensureColumn(new rex_sql_column('embedUrl', 'text', false, ''))
```

lief die Installation durch.

**Comment by alxndr-w** [comment]
Das kommt von der Verwendung von MariaDB lokal, hier werden Defaults nicht korrekt gesetzt.

Es muss immer `\'\''` durch `''` ersetzt werden. Siehe z.B. hier: https://github.com/yakamara/ydeploy/issues/39

**Comment by alxndr-w** [comment]
Ich tendiere zu "grundsätzlich ersetzen"
