### ISSUE TITLE
Ist "sprogcard" richtig geschrieben?

### ISSUE THREAD

**Issue by christophboecker** [alexplusde/wenns_sein_muss#58]
Meine IDE meldet

<img width="645" alt="grafik" src="https://github.com/user-attachments/assets/3f091f13-75da-4e82-810a-f02d11f2f75f">

zu diesem Code:
https://github.com/alexplusde/wenns_sein_muss/blob/2953aa60f994ab719a6bf47cfba5f2f0e8eaf6d2/lib/Wsm.php#L233-L238

Auch wenn es um eine Funktion geht, deren Verfügbarkeit vorher abgefragt wird, wäre dennoch die Schreibweise m.E. falsch, da PHP zuerst im Namespace auflöst (siehe Fehlermeldung). Wäre nicht `\sprogcard` richtig?

In dem Fall meckert meine IDE nämlich - und dann zu Recht - an:

<img width="535" alt="grafik" src="https://github.com/user-attachments/assets/6e8c8d41-a8e4-4cce-b07f-a1ac2a971ec3">

**Comment by alxndr-w** [comment]
Hat meine nicht gemeldet, aber in dem Addon scheint eh mein VSCode und phpcsfixer konsequent das Melden von Fehlern zu vermeiden. Warum auch immer.

**Comment by alxndr-w** [comment]
closed in #59, Merci.
