### ISSUE TITLE
`5.0.1` 1170 BLOB/TEXT column 'domain_id' used in key specification without a key length

### ISSUE THREAD

**Issue by alxndr-w** [alexplusde/wenns_sein_muss#63]
AddOn wenns_sein_muss konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_wenns_sein_muss_domain` CHANGE `domain_id` `domain_id` text NOT NULL , CHANGE `privacy_policy_id` `privacy_policy_id` int NOT NULL , CHANGE `imprint_id` `imprint_id` int NOT NULL ;" using params []! SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'domain_id' used in key specification without a key length

**Comment by ansichtsache** [comment]
same ;–)

**Comment by alxndr-w** [comment]
Kannst du mir einen Systembericht posten?

**Comment by alxndr-w** [comment]
https://redaxo.org/doku/main/system

**Comment by ansichtsache** [comment]
`<details>
<summary>System report (REDAXO 5.17.1, PHP 8.2.18, MariaDB 10.3.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.1     |


| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.2.18                         |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |


| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.3.39                |
| Character set | utf8mb4                        |
|       Warning | Die verwendete MariaDB-Version 10.3.39 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/130.0 |
|      Protocol | HTTP/1.1      |
|         HTTPS | no            |


| Packages               |            |
| ---------------------: | :--------- |
|                adminer | 2.0.2      |
|                 backup | 2.9.1      |
|               be_style | 3.4.1      |
|    be_style/customizer | 3.3.1      |
|        be_style/redaxo | 3.4.1      |
|                bloecks | 4.0.2      |
|       bloecks/cutncopy | 4.0.2      |
|      bloecks/dragndrop | 4.0.2      |
|                   cke5 | 6.1.0      |
|                cropper | 2.0.3      |
|                install | 2.12.1     |
|                 mblock | 3.4.13     |
|          media_manager | 2.16.0     |
|              mediapool | 2.14.0     |
|               metainfo | 2.11.0     |
|                  mform | 8.0.3      |
|          modulsammlung | 4.21.0     |
|       navigation_array | 4.0.0      |
|                  neues | 5.0.1      |
|              phpmailer | 2.13.1     |
|                project | dev        |
|       quick_navigation | 8.1.3      |
|              search_it | 6.11.2     |
| search_it/autocomplete | 6.11.2     |
|    search_it/plaintext | 6.11.2     |
|        search_it/stats | 6.11.2     |
|                  sprog | 1.5.1      |
|              structure | 2.17.1     |
|      structure/content | 2.17.1     |
|             theme_lock | 1.0.0      |
|       uikit_collection | 4.0.0      |
|               uploader | 2.4.2      |
|                    url | 2.1.0      |
|                  users | 2.11.0     |
|                  yform | 4.2.1      |
|            yform/email | 4.2.1      |
|          yform/manager | 4.2.1      |
|             yform/rest | 4.2.1      |
|            yform/tools | 4.2.1      |
|            yform_field | 2.7.0      |
|               yrewrite | 2.10.0     |

</details>`

**Comment by alxndr-w** [comment]
Check mal bitte die 5.0.2, darin sollte das Problem behoben sein.

**Comment by ansichtsache** [comment]
sorry, aber der fehler taucht bei der 5.0.2 auf

**Comment by alxndr-w** [comment]
Das wundert mich, denn ich habe tatsächlich Korrekturen aufgenommen hier:

https://github.com/alexplusde/wenns_sein_muss/blob/c0271d5ede9b319c0655458ff0bf74811773f72a/install.php#L3-L9

und hier

https://github.com/alexplusde/wenns_sein_muss/blob/c0271d5ede9b319c0655458ff0bf74811773f72a/install/rex_wenns_sein_muss_domain.json#L25-L38

Könnte ich evtl. Zugriff zum Projekt erhalten, um mir das Mal genauer anzusehen?

PS: Im Systembericht folgender Hinweis bei dir:

> Die verwendete MariaDB-Version 10.3.39 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden.

**Comment by ansichtsache** [comment]
PM über slack

**Comment by alxndr-w** [comment]
Workaround aktuell: unique-Index direkt in der Datenbank (z.B. via Adminer) an der Tabelle `rex_wenns_sein_muss_domain` löschen und dann installieren/updaten.

**Comment by alxndr-w** [comment]
Es scheint nur bei Updates zu Problemen zu kommen, nicht bei frischer Installation.
